server:
  port: 8009
mybatis:
  config-location:  classpath:mybatis/mybatis.cfg.xml
  mapper-locations: classpath:mybatis/mapper/**/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shapecode?useUnicode=true&characterEncoding=utf8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.biji.puppeteer.shapecode.dao.model

elasticsearch:
  hostname: localhost   #elasticsearch服务器地址
  port: 9200                  #elasticsearch服务器端口
  index: index