server:
  port: 5001

spring:
  application:
    name: microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zbj1193959702/microservice-cloud-config.git